package com.northsea.dao;

import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.northsea.entity.Unit;
import com.northsea.entity.User;
import org.apache.logging.log4j.util.Strings;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * @Author BenSitu
 * @CreateDate 2022/10/14
 * @Description
 */
@SpringBootTest
public class UnitDaoTest {

    @Autowired
    private UnitDao unitDao;

    @Test
    void getByIdTest() {
        System.out.println(unitDao.selectById(1));
    }

    @Test
    void getAllTest() {
        System.out.println(unitDao.selectList(null));
    }

    @Test
    void getByConditionTest() {
        String name = "台";
        IPage<Unit> page = new Page<Unit>(1, 10);
        LambdaQueryWrapper<Unit> lambdaQueryWrapper = new LambdaQueryWrapper<Unit>();
        lambdaQueryWrapper.like(Strings.isNotEmpty(name), Unit::getName, name);
        unitDao.selectPage(page, lambdaQueryWrapper);
    }

    @Test
    public void insertUnitTest(){
        Unit unit = new Unit();
        unit.setUnitId(00);
        unit.setName("美");
        unitDao.saveWithAutoGeneratedId(unit);
    }

}
