package com.northsea.service;

import com.baomidou.mybatisplus.extension.service.IService;
import com.northsea.entity.Unit;

/**
 * @Author BenSitu
 * @CreateDate 2022/10/14
 * @Description
 */

public interface UnitService extends IService<Unit> {
    public int saveWithAutoGeneratedId(Unit unit);
}
