package com.northsea.service.impl;

import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import com.northsea.dao.UnitDao;
import com.northsea.entity.Unit;
import com.northsea.service.UnitService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * @Author BenSitu
 * @CreateDate 2022/10/14
 * @Description
 */
@Service
public class UnitServiceImpl extends ServiceImpl<UnitDao, Unit> implements UnitService {

    @Autowired
    private UnitDao unitDao;

    @Transactional
    @Override
    public int saveWithAutoGeneratedId(Unit unit) {
//        return unitDao.saveWithAutoGeneratedId(unit) > 0;
        return 1;
    }

}
