package com.northsea.dao;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.northsea.entity.Unit;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * @Author BenSitu
 * @CreateDate 2022/10/14
 * @Description
 */
@Mapper
public interface UnitDao extends BaseMapper<Unit> {

//    @Insert()
//    int insertUnit(Unit unit);

    /**
     *
     * @param unit
     * @return
     */
    public int saveWithAutoGeneratedId(@Param(value = "unit") Unit unit);
}
